### ISSUE TITLE
/v2.0/database-notorm勘误

### ISSUE THREAD

**Issue by Andrew8102** [phalapi/phalapi-wiki#1]
## 该问题是怎么引起的？

/v2.0/database-notorm勘误
2.x 的Model类名 | 对应的文件 | 自动匹配的表名 | 自动添加表前缀的完整表名
-- | -- | -- | --
App\Model\User | ./src/app/Model/User.php | user | tbl_user
App\ModelUser\Friends | ./src/app/Model/User/Friends.php | user_friends | tbl_user_friends
App\User\Model\Friends | ./src/app/user/Model/Friends.php | friends | tbl_friends
App\User\Model\User\Friends | ./src/app/user/Model/User/Friends.php | user_friends | tbl_user_friends

第二行类名是否应为`App\Model\User\Friends`？
11个月前在gitee镜像反应过但没人回复

顺路在github上提个issue

**Comment by williamjiangsa** [comment]
你好，感谢提出这个错误，这个是说明文档的编辑错误，已经修正，谢谢！有任何Issue欢迎提出一起改进！
Hello, thanks for raising this error, this is an editorial error,  it has been corrected, thank you! Any Issue is welcome to propose, we will improve it together!
